export const GET_FILMS_START = 'GET_FILMS_START';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_SINGLE_FILM_START = 'GET_SINGLE_FILM_START';
export const GET_SINGLE_FILM_SUCCESS = 'GET_SINGLE_FILM_SUCCESS';
export const GET_REVIEWS = 'GET_REVIEWS';
export const CHANGE_CURRENT_CATEGORY = 'CHANGE_CURRENT_CATEGORY';

export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const ADD_TO_MY_LIST = 'ADD_TO_MY_LIST';
export const ADD_FILM = 'ADD_FILM';
export const REMOVE_FROM_MY_LIST = 'REMOVE_FROM_MY_LIST';